# Generated by Django 5.1.7 on 2025-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="description",
            field=models.TextField(default="No Description"),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
